### ISSUE TITLE
Chatgroepen

### ISSUE THREAD

**Issue by nielsasberg** [RikvanToor/BMN#10]
Voor elk nummer een chatgroep die automatisch wordt aangemaakt met de goede muzikanten, plus toegang voor alle commissieleden

**Comment by RikvanToor** [comment]
Ik ben hier eigenlijk niet helemaal voor. De website bevatte tot vorig jaar een chatfunctie per nummer, maar die werd eigenlijk niet gebruikt, iedereen ging gewoon naar WhatsApp. Nu zou het natuurlijk in een appvorm gemaakt kunnen worden, maar vergeet niet dat we waarschijnlijk geen iOS app kunnen gaan publiceren

**Comment by nielsasberg** [comment]
Ja dat is wel waar, dan zouden mensen met iOS puur via de website moeten chatten. Maar als we die website responsive maken zou het wel kunnen toch? Het is vooral handig voor de commissie om alles goed bij te kunnen houden denk ik. Maar ik ben wel eens dat het geen hoge prioriteit heeft

**Comment by nielsasberg** [comment]
Zo te zien is het ook onmogelijk om op iOS push notifications te sturen vanuit iets anders dan een dedicated app (dus geen web app, ook niet als je op de home page opslaat) - dus het lijkt me dan idd beter om dit niet toe te voegen

**Comment by bacusters** [comment]
Zo te zien is dit dus niet haalbaar
