### ISSUE TITLE
Setlist bekijken & maken

### ISSUE THREAD

**Issue by nielsasberg** [RikvanToor/BMN#11]
- Bekijken van de setlist, sorteerbaar op bijv. naam en duur
- Bekijken en vaststellen van de setlistvolgorde (met automatische detectering als iemand 2 nummers achter elkaar zou doen? en misschien als een muzikant alleen maar in de eerste of tweede helft speelt ofzo?)
- Een overzicht kunnen zien van alle deelnemers met podiumtijd, aantal nummers en score (0.75 * podiumtijd / max + 0.25 * nummers / max ofzo), uiteraard sorteerbaar op alle eigenschappen

**Comment by bacusters** [comment]
Laatste twee puntjes ondergebracht in #31 en #32

**Comment by bacusters** [comment]
PR is geopend
