### ISSUE TITLE
Mogelijk maken user (naam muzikant) op te slaan bij suggestie

### ISSUE THREAD

**Issue by nielsasberg** [RikvanToor/BMN#54]
Op dit moment wordt bij het invoeren van een suggestie niet opgeslagen wie de suggestie heeft gedaan. Wellicht zou het daarom een goed idee zijn om een soort **anoniem-switch** toe te voegen aan het suggestieformulier, waarbij kan worden gekozen of de naam van de muzikant (user) wordt opgeslagen bij de suggestie.

Anders is er voor muzikanten niet veel reden om suggesties op te geven, dit gebeurt natuurlijk voornamelijk omdat mensen die zelf willen spelen :)

**Comment by Atleast1** [comment]
Is nog niet besproken door de commissie hoe zij dit graag ingevuld ziet.

**Comment by RikvanToor** [comment]
Moet er dan wel een anoniem switch zijn? Misschien wil je dat dit niet anoniem kan. Wat wordt er gedaan met de suggesties die al ingevoerd zijn? Ik dacht eigenlijk dat er al namen bij werden opgeslagen..

**Comment by Atleast1** [comment]
Anoniem switch is niet nodig! Suggesties die al gedaan zijn zullen we een gepaste manier voor zoeken. Was nog geen mogelijkheid namen te koppelen. Dit is wel echt urgent!
